# Generated by Django 4.2.19 on 2025-03-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_cart_created_at_remove_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
