# Generated by Django 4.2.17 on 2025-03-15 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedbacks', to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feedbacks', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive 😀'), ('Neutral', 'Neutral 😐'), ('Negative', 'Negative 😞')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('customer', 'product')},
        ),
    ]
