# Generated by Django 4.2.17 on 2025-03-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_feedback_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('customer', 'product')},
        ),
    ]
