# Generated by Django 4.2.19 on 2025-03-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment_score',
        ),
    ]
