# Generated by Django 4.2.19 on 2025-03-16 02:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_feedback_created_at_remove_feedback_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive 😀'), ('Neutral', 'Neutral 😐'), ('Negative', 'Negative 😞')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
